[config]
schemaVersion = "0.0.1"

[package]
namespace = "MGReturns"
name = "ENVY"
versionNumber = "1.1.0"
description = "A plugin to allow ReturnOfModding plugins greater control of their environment."
websiteUrl = "https://github.com/AndreLouisIssa/RoRR-ENVY"
containsNsfwContent = false

[package.dependencies]
ReturnOfModding-ReturnOfModding = "1.0.38"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "risk-of-rain-returns", ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
