[config]
schemaVersion = "0.0.1"

[package]
namespace = "SGG_Modding"
name = "ENVY"
versionNumber = "1.1.0"
description = "A plugin to allow ReturnOfModding plugins greater control of their environment."
websiteUrl = "https://github.com/SGG-Modding/ENVY"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.28"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "libraries", "mods" ]
